/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LDAdmin;

import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.UserAccount.UserAccount;
import MainPages.LoginPage;
import static java.time.Clock.system;
import javax.swing.JFrame;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author narasimhareddypotlapati
 */
public class LDAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LDAdminJPanel
     */
    private EcoSystem ecosystem;
    private UserAccount useraccount;
    private DB4OUtil dB4OUtil;
    public LDAdminJPanel(EcoSystem ecosystem,DB4OUtil dB4OUtil, UserAccount UA) {
        initComponents();
         this.ecosystem=ecosystem;
         this.dB4OUtil = dB4OUtil;
         this.useraccount = UA;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Adminlabel = new javax.swing.JLabel();
        SysAdminImage = new javax.swing.JLabel();
        Adminimage = new javax.swing.JLabel();
        SysAdminlabel = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        Adminlabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Adminlabel.setForeground(new java.awt.Color(255, 255, 255));
        Adminlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Adminlabel.setText("Admin");

        SysAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminx64.png"))); // NOI18N
        SysAdminImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SysAdminImageMousePressed(evt);
            }
        });

        Adminimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sysadminx64.png"))); // NOI18N
        Adminimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminimageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminimageMousePressed(evt);
            }
        });

        SysAdminlabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        SysAdminlabel.setForeground(new java.awt.Color(255, 255, 255));
        SysAdminlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SysAdminlabel.setText("Sys Admin");

        back.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logoutx32.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SysAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Adminlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Adminimage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SysAdminlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addGap(313, 313, 313))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Adminimage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SysAdminlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Adminlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SysAdminImage))
                .addGap(122, 122, 122)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(520, 520, 520))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdminimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminimageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminimageMouseClicked

    private void AdminimageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminimageMousePressed
        // TODO add your handling code here:
        boolean flag = true;
        boolean admin = true;
        //new LoginPage(flag,admin).show();
    }//GEN-LAST:event_AdminimageMousePressed

    private void SysAdminImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SysAdminImageMousePressed
        // TODO add your handling code here:
        boolean flag = true;
        boolean sysadmin = true;
        //useraccount.getRole().createWorkArea(userProcessContainer, useraccount, null, null, ecosystem,dB4OUtil);
    }//GEN-LAST:event_SysAdminImageMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        // TODO add your handling code here:
        JFrame frame = (JFrame) getWindowAncestor(this);
        frame.dispose();
        LDAdminJPanel.super.setVisible(false);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_backMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adminimage;
    private javax.swing.JLabel Adminlabel;
    private javax.swing.JLabel SysAdminImage;
    private javax.swing.JLabel SysAdminlabel;
    private javax.swing.JLabel back;
    // End of variables declaration//GEN-END:variables
}
