/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LimbAdmin;

/**
 *
 * @author narasimhareddypotlapati
 */
public class LimbAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LimbAdminJPanel
     */
    public LimbAdminJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SysAdminImage = new javax.swing.JLabel();
        Adminimage = new javax.swing.JLabel();

        SysAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminx64.png"))); // NOI18N
        SysAdminImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SysAdminImageMousePressed(evt);
            }
        });

        Adminimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sysadminx64.png"))); // NOI18N
        Adminimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminimageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminimageMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(Adminimage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(165, 165, 165)
                    .addComponent(SysAdminImage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(194, Short.MAX_VALUE)
                .addComponent(Adminimage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(SysAdminImage)
                    .addContainerGap(118, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SysAdminImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SysAdminImageMousePressed
        // TODO add your handling code here:
        boolean flag = true;
        boolean sysadmin = true;
        //new LoginPage(flag,sysadmin).show();
    }//GEN-LAST:event_SysAdminImageMousePressed

    private void AdminimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminimageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminimageMouseClicked

    private void AdminimageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminimageMousePressed
        // TODO add your handling code here:
        boolean flag = true;
        boolean admin = true;
        //new LoginPage(flag,admin).show();
    }//GEN-LAST:event_AdminimageMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adminimage;
    private javax.swing.JLabel SysAdminImage;
    // End of variables declaration//GEN-END:variables
}
