/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPages;

/**
 *
 * @author ms
 */
public class InfoPage extends javax.swing.JFrame {

    /**
     * Creates new form InfoPage
     */
    public InfoPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Informationlbl1 = new javax.swing.JLabel();
        Informationlbl2 = new javax.swing.JLabel();
        Informationlbl3 = new javax.swing.JLabel();
        Titlelabel = new javax.swing.JLabel();
        lblBgd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Informationlbl1.setBackground(new java.awt.Color(255, 255, 255));
        Informationlbl1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        Informationlbl1.setForeground(new java.awt.Color(255, 255, 255));
        Informationlbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Informationlbl1.setText("Every donor can save 8 lives and enhance more than 75 lives");
        jPanel1.add(Informationlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 590, 52));

        Informationlbl2.setBackground(new java.awt.Color(255, 255, 255));
        Informationlbl2.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        Informationlbl2.setForeground(new java.awt.Color(255, 255, 255));
        Informationlbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Informationlbl2.setText("26  people are dying daily waiting for a transplant");
        jPanel1.add(Informationlbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 540, 44));

        Informationlbl3.setBackground(new java.awt.Color(255, 255, 255));
        Informationlbl3.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        Informationlbl3.setForeground(new java.awt.Color(255, 255, 255));
        Informationlbl3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Informationlbl3.setText("46,528 transplants were performed in 2022");
        jPanel1.add(Informationlbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 220, 500, 44));

        Titlelabel.setFont(new java.awt.Font("Times New Roman", 1, 38)); // NOI18N
        Titlelabel.setForeground(new java.awt.Color(255, 255, 255));
        Titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titlelabel.setText("Insights");
        jPanel1.add(Titlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 24, 720, 60));

        lblBgd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MicrosoftTeams-image_2_1_1100x800.png"))); // NOI18N
        jPanel1.add(lblBgd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Informationlbl1;
    private javax.swing.JLabel Informationlbl2;
    private javax.swing.JLabel Informationlbl3;
    private javax.swing.JLabel Titlelabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBgd;
    // End of variables declaration//GEN-END:variables
}
