/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPages;

//import javafx.scene.paint.Color;
import Backend.DB4OUtil.DB4OUtil;
import Backend.EcoSystem;
import Backend.Employee.Employee;
import Backend.Enterprise.Enterprise;
import Backend.NGO.NGO;
import Backend.Organization.LabOrganization;
import Backend.Organization.Organization;
import Backend.Role.SystemAdminRole;
import Backend.Role.LDAdminRole;
import Backend.User.User;

import Backend.UserAccount.UserAccount;

import Backend.WorkQueue.CoordinatorTestWorkRequest;
import UI.Admin.AdminDashBoardJPanel;
import UI.Donor.DonorDashBoardJPanel;
import UI.Receiver.ReceiverDashBoardJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Backend.JavaMailUtil;
import Backend.Email;

/**
 *
 * @author ms
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private String verificationCode = JavaMailUtil.getRandomCode();
    private Boolean check = false;
    public LoginPage() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        ButtonsignUp.setVisible(false);
        //signUpBottomTextBox.setVisible(false);
        TextFieldemailId.setVisible(false);
        emailIdJlabel.setVisible(false);
        jButton1.setVisible(false);
        NGOCbx.setVisible(false);
   //     emailIdSeparator.setVisible(false);
        JTextFieldname.setVisible(false);
   //     nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        ButtonsignIn.setVisible(true);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        //signInBottomTextBox.setVisible(true);
        ButtonGroup group = new ButtonGroup();
        group.add(RadioButtonDonor);
        group.add(RadioButtonreceiver);
        
    }

    public LoginPage(boolean sysAdminPressed, boolean employee) {
        initComponents();        
         system = dB4OUtil.retrieveSystem();
        TextFieldemailId.setVisible(false);
        emailIdJlabel.setVisible(false);
        //emailIdSeparator.setVisible(false);
        JTextFieldname.setVisible(false);
        //nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        ButtonsignIn.setVisible(true);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        
        //signInBottomTextBox.setVisible(true);
        ButtonGroup group = new ButtonGroup();
        group.add(RadioButtonDonor);
        group.add(RadioButtonreceiver);
        if(sysAdminPressed==true){
            ButtonsignUp.setVisible(false);
            LabelTopsignUp.setVisible(false);
            LabeTopsignIn.setVisible(false);
        } //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblbgd = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        passwordlabel6 = new javax.swing.JLabel();
        ButtonsignIn = new javax.swing.JLabel();
        LabelerrorthrownforerrorPassword = new javax.swing.JLabel();
        JTextFieldname = new javax.swing.JTextField();
        Fieldpassword = new javax.swing.JPasswordField();
        JTextFielduserName = new javax.swing.JTextField();
        emailIdJlabel = new javax.swing.JLabel();
        ButtonsignUp = new javax.swing.JLabel();
        RadioButtonreceiver = new javax.swing.JRadioButton();
        LabelerrorthrownForEmailId = new javax.swing.JLabel();
        TextFieldemailId = new javax.swing.JTextField();
        RadioButtonDonor = new javax.swing.JRadioButton();
        nameLabel = new javax.swing.JLabel();
        buttonsexit = new javax.swing.JLabel();
        Usernamelabel = new javax.swing.JLabel();
        Titlelabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabelTopsignUp = new javax.swing.JLabel();
        LabeTopsignIn = new javax.swing.JLabel();
        NGOCbx = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnverifyEmail = new javax.swing.JButton();
        txtVerifyCode = new javax.swing.JTextField();
        lblBgd = new javax.swing.JLabel();

        lblbgd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WorkTIme.png"))); // NOI18N

        setLocationByPlatform(true);
        setUndecorated(true);

        userProcessContainer.setBackground(new java.awt.Color(51, 204, 255));
        userProcessContainer.setMinimumSize(new java.awt.Dimension(860, 600));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(854, 600));
        userProcessContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordlabel6.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        passwordlabel6.setForeground(new java.awt.Color(255, 255, 255));
        passwordlabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        passwordlabel6.setText("Password");
        jPanel1.add(passwordlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 160, 20));

        ButtonsignIn.setBackground(new java.awt.Color(30, 59, 91));
        ButtonsignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonsignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in.png"))); // NOI18N
        ButtonsignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonsignInMousePressed(evt);
            }
        });
        jPanel1.add(ButtonsignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 730, 130, 50));

        LabelerrorthrownforerrorPassword.setBackground(new java.awt.Color(204, 204, 204));
        LabelerrorthrownforerrorPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelerrorthrownforerrorPassword.setForeground(new java.awt.Color(255, 51, 51));
        LabelerrorthrownforerrorPassword.setText("!");
        LabelerrorthrownforerrorPassword.setToolTipText("Password Should be more than 6 character");
        jPanel1.add(LabelerrorthrownforerrorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 20, 30));

        JTextFieldname.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        JTextFieldname.setBorder(null);
        JTextFieldname.setCaretColor(new java.awt.Color(30, 59, 92));
        JTextFieldname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextFieldnameFocusGained(evt);
            }
        });
        JTextFieldname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFieldnameActionPerformed(evt);
            }
        });
        jPanel1.add(JTextFieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 250, 30));

        Fieldpassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        Fieldpassword.setBorder(null);
        Fieldpassword.setCaretColor(new java.awt.Color(30, 59, 92));
        Fieldpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldpasswordFocusGained(evt);
            }
        });
        Fieldpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldpasswordKeyReleased(evt);
            }
        });
        jPanel1.add(Fieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 590, 250, 30));

        JTextFielduserName.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        JTextFielduserName.setBorder(null);
        JTextFielduserName.setCaretColor(new java.awt.Color(30, 59, 92));
        JTextFielduserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JTextFielduserNameFocusGained(evt);
            }
        });
        JTextFielduserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextFielduserNameActionPerformed(evt);
            }
        });
        jPanel1.add(JTextFielduserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 250, 30));

        emailIdJlabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        emailIdJlabel.setForeground(new java.awt.Color(255, 255, 255));
        emailIdJlabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        emailIdJlabel.setText("Email Id");
        jPanel1.add(emailIdJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 160, 20));

        ButtonsignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ButtonsignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-sign-up-100.png"))); // NOI18N
        ButtonsignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ButtonsignUpMousePressed(evt);
            }
        });
        jPanel1.add(ButtonsignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 730, 140, 70));

        RadioButtonreceiver.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        RadioButtonreceiver.setForeground(new java.awt.Color(255, 255, 255));
        RadioButtonreceiver.setText("Receiver");
        RadioButtonreceiver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(RadioButtonreceiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 690, 90, 20));

        LabelerrorthrownForEmailId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelerrorthrownForEmailId.setForeground(new java.awt.Color(255, 0, 0));
        LabelerrorthrownForEmailId.setText("!");
        LabelerrorthrownForEmailId.setToolTipText("Please enter a valid Email ID");
        jPanel1.add(LabelerrorthrownForEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 640, 20, 30));

        TextFieldemailId.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        TextFieldemailId.setBorder(null);
        TextFieldemailId.setCaretColor(new java.awt.Color(30, 59, 92));
        TextFieldemailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextFieldemailIdFocusGained(evt);
            }
        });
        TextFieldemailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldemailIdActionPerformed(evt);
            }
        });
        TextFieldemailId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextFieldemailIdKeyReleased(evt);
            }
        });
        jPanel1.add(TextFieldemailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 640, 250, 30));

        RadioButtonDonor.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        RadioButtonDonor.setForeground(new java.awt.Color(255, 255, 255));
        RadioButtonDonor.setText("Donor");
        RadioButtonDonor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(RadioButtonDonor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 690, 80, -1));

        nameLabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nameLabel.setText("Name");
        jPanel1.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 160, 20));

        buttonsexit.setBackground(new java.awt.Color(255, 255, 255));
        buttonsexit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        buttonsexit.setForeground(new java.awt.Color(255, 255, 255));
        buttonsexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonsexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logoutx32.png"))); // NOI18N
        buttonsexit.setText("Logout\n");
        buttonsexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonsexitMousePressed(evt);
            }
        });
        jPanel1.add(buttonsexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 110, 40));

        Usernamelabel.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Usernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        Usernamelabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Usernamelabel.setText("Username");
        jPanel1.add(Usernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 160, 20));

        Titlelabel.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        Titlelabel.setForeground(new java.awt.Color(255, 255, 255));
        Titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titlelabel.setText("Make a Difference");
        jPanel1.add(Titlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 70));

        jLabel1.setText(" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        LabelTopsignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelTopsignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-sign-up-100.png"))); // NOI18N
        LabelTopsignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabelTopsignUpMousePressed(evt);
            }
        });
        jPanel1.add(LabelTopsignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 140, 70));

        LabeTopsignIn.setBackground(new java.awt.Color(30, 59, 91));
        LabeTopsignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabeTopsignIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign in.png"))); // NOI18N
        LabeTopsignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LabeTopsignInMousePressed(evt);
            }
        });
        jPanel1.add(LabeTopsignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 130, 50));

        NGOCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select any NGO---", "Liver NGO", "Limp NGO" }));
        jPanel1.add(NGOCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 690, -1, -1));

        jButton1.setText("NGO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, -1, -1));

        btnverifyEmail.setText("Verify");
        btnverifyEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverifyEmailActionPerformed(evt);
            }
        });
        jPanel1.add(btnverifyEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 640, -1, -1));

        txtVerifyCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVerifyCodeActionPerformed(evt);
            }
        });
        jPanel1.add(txtVerifyCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 110, -1));

        lblBgd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/background.jpg"))); // NOI18N
        jPanel1.add(lblBgd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 790));

        userProcessContainer.add(jPanel1, "card20");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   int xx,xy; 
    private void buttonsexitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsexitMousePressed
        // TODO add your handling code here:
        LoginPage.super.dispose();
    }//GEN-LAST:event_buttonsexitMousePressed

    private void TextFieldemailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldemailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldemailIdActionPerformed

    private void FieldpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldpasswordFocusGained
        // TODO add your handling code here:
       Fieldpassword.setText("");
    }//GEN-LAST:event_FieldpasswordFocusGained

    private void JTextFielduserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFielduserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFielduserNameActionPerformed

    private void JTextFielduserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextFielduserNameFocusGained
        // TODO add your handling code here:
       JTextFielduserName.setText("");
    }//GEN-LAST:event_JTextFielduserNameFocusGained

    private void TextFieldemailIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextFieldemailIdFocusGained
        // TODO add your handling code here:
     TextFieldemailId.setText("");
    }//GEN-LAST:event_TextFieldemailIdFocusGained

    private void ButtonsignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonsignUpMousePressed
        // TODO add your handling code here:
           
           try {
//            if (!checkUserIdExists(userNameJTextField.getText())){
//            JOptionPane.showMessageDialog(null, "UserName Already Present","Warning",JOptionPane.WARNING_MESSAGE);
//            return;
//            }
            
            if (Fieldpassword.getText().length() < 6  ){
            
            JOptionPane.showMessageDialog(null, "Plz enter correct password(atleast 1 char and 1 number with 6 digits","Warning",JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            if ( LabelerrorthrownForEmailId.isVisible() == true) {
                
              JOptionPane.showMessageDialog(null, "Email id is wrong","Error",JOptionPane.ERROR_MESSAGE);
              return;   
            
            }
            // RAJA - VALIDATION to select alteast one buttons
            
            if(check){
                if (RadioButtonDonor.isSelected() || RadioButtonreceiver.isSelected() || NGOCbx.isShowing() ) {
            
            
            User user = system.getUserDirectory().addUser();
            user.setUserName(JTextFielduserName.getText());
            user.setEmailId(TextFieldemailId.getText());
            user.setPassword(Fieldpassword.getText());
            user.setName(JTextFieldname.getText());

            if (RadioButtonDonor.isSelected() == true) {
                user.setType('d');
            } 
            else if  (RadioButtonreceiver.isSelected() == true){
                user.setType('r');
            }
            else {   
                
                if(NGOCbx.getSelectedItem() == "Liver NGO"){
                    Employee employee = system.getEmployeeDirectory().createEmployee(JTextFieldname.getText());
        UserAccount ua = system.getUserAccountDirectory().createUserAccount(JTextFielduserName.getText(), Fieldpassword.getText(), employee, new SystemAdminRole());
        
                    }
            
                else{
                    user.setType('a');
                    }
            }
            JOptionPane.showMessageDialog(null, "User Account has been created Successfully");
            TextFieldemailId.setText("");
            Fieldpassword.setText("");
            JTextFielduserName.setText("");
            JTextFieldname.setText("");
            }
            else {
            
            JOptionPane.showMessageDialog(null, "Please select a Donor or Receiver","Error",JOptionPane.ERROR_MESSAGE);
              return; 
            
            }
            }else{
                            JOptionPane.showMessageDialog(null, "pls verify your mail");

            }
            
           }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ButtonsignUpMousePressed
   
    private boolean checkUserIdExists(String userName) {
        try {
        if (system.getUserDirectory().checkIfUsernameIsUnique(userName)) {
            if (system.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {
                for (NGO ngo : system.getngoList()) {
                    for (Enterprise enterprise : ngo.getEnterpriseDirectory().getEnterpList()) {
                        if (enterprise.getUserAccountDirectory().checkIfUsernameIsUnique(userName)) {

                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                return organization.getUserAccountDirectory().checkIfUsernameIsUnique(userName);

                            }

                        } else {
                            return false;

                        }
                    }
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
         return false;
    }
    private void JTextFieldnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JTextFieldnameFocusGained
        // TODO add your handling code here:
        JTextFieldname.setText("");
    }//GEN-LAST:event_JTextFieldnameFocusGained

    private void JTextFieldnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextFieldnameActionPerformed

    private void ButtonsignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonsignInMousePressed
        // TODO add your handling code here:
        // Get user name
        try {
        User user;
        System.out.println(system.getUserDirectory()+"Hi ra mams" + JTextFielduserName.getText()+" "+Fieldpassword.getText());
        user = system.getUserDirectory().authenticateUser(JTextFielduserName.getText(), Fieldpassword.getText());
        System.out.println(user+"this here");
        if(user!=null){

            if (user.getType() == 'd') {

                DonorDashBoardJPanel donorPanel = new DonorDashBoardJPanel(dB4OUtil,system,user);
                userProcessContainer.add("DonorDashBoardJPanel",donorPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                donorPanel.setVisible(true);

            } else if (user.getType() == 'r') {
                ReceiverDashBoardJPanel receiverPanel = new ReceiverDashBoardJPanel(dB4OUtil,system,user);
                userProcessContainer.add("ReceiverDashBoardJPanel",receiverPanel);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
                receiverPanel.setVisible(true);
            }
            
                
            
        }
        else{

            String userName = JTextFielduserName.getText();
            // Get Password
            char[] passwordCharArray = Fieldpassword.getPassword();
            String password = String.valueOf(passwordCharArray);
            System.out.println(system.getUserAccountDirectory());
            //Step1: Check in the system admin user account directory if you have the user
            UserAccount userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);
            System.out.println(userAccount);
            System.out.println("nee mama");
            Enterprise inEnterprise=null;
            Organization inOrganization=null;

            if(userAccount==null){
                //Step 2: Go inside each ngo and check each enterprise
                
                for(NGO ngo:system.getngoList()){
                    //Step 2.a: check against each enterprise
                    if(ngo.getEnterpriseDirectory().getEnterpList() != null){
                    for(Enterprise enterprise:ngo.getEnterpriseDirectory().getEnterpList()){
                        userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                        if(userAccount==null){
                            //Step 3:check against each organization for each enterprise
                            for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
                                userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                                if(userAccount!=null){
                                    inEnterprise=enterprise;
                                    inOrganization=organization;
                                    break;
                                }
                            }

                        }
                        else{
                            inEnterprise=enterprise;
                            break;
                        }
                        if(inOrganization!=null){
                            break;
                        }
                    }
                    }
                    if(inEnterprise!=null){
                        break;
                    }
                }
            }

            if(userAccount==null){
                JOptionPane.showMessageDialog(null, "Invalid credentials");
                return;
            }
            else{
                System.out.println(inEnterprise);
                System.out.println("nee mama");
                System.out.println(userAccount.getRole());
                userAccount.getRole().createWorkArea(userProcessContainer, userAccount, inOrganization, inEnterprise, system,dB4OUtil);

            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_ButtonsignInMousePressed

    private void TextFieldemailIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldemailIdKeyReleased
        // TODO add your handling code here:
        
        String patternForEmail = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";
        String emailID = TextFieldemailId.getText();
        Pattern patternForEmailId = Pattern.compile(patternForEmail);
        Matcher matcherForEmailId = patternForEmailId.matcher(emailID);
        if (matcherForEmailId.matches() == false) {
            LabelerrorthrownForEmailId.setVisible(true);
        } else {
            LabelerrorthrownForEmailId.setVisible(false);
        }
    }//GEN-LAST:event_TextFieldemailIdKeyReleased

    private void FieldpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldpasswordKeyReleased
        // TODO add your handling code here:
        if (Fieldpassword.getText().length() < 6) {
            LabelerrorthrownforerrorPassword.setVisible(true);
        } else {
            LabelerrorthrownforerrorPassword.setVisible(false);
        }
        
    }//GEN-LAST:event_FieldpasswordKeyReleased

    private void LabelTopsignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelTopsignUpMousePressed
        // TODO add your handling code here:
        ButtonsignUp.setVisible(true);
        //signUpBottomTextBox.setVisible(true);
        ButtonsignIn.setVisible(false);
        //signInBottomTextBox.setVisible(false);
        TextFieldemailId.setVisible(true);
        emailIdJlabel.setVisible(true);
        //emailIdSeparator.setVisible(true);
        RadioButtonDonor.setVisible(true);
        RadioButtonreceiver.setVisible(true);
        JTextFieldname.setVisible(true);
        //nameSeparator.setVisible(true);
        nameLabel.setVisible(true);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        NGOCbx.setVisible(false);
        btnverifyEmail.setVisible(true);
        txtVerifyCode.setVisible(true);
        jButton1.setVisible(false);
    }//GEN-LAST:event_LabelTopsignUpMousePressed

    private void LabeTopsignInMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabeTopsignInMousePressed
        // TODO add your handling code here:
        ButtonsignUp.setVisible(false);
        //signUpBottomTextBox.setVisible(false);
        TextFieldemailId.setVisible(false);
        emailIdJlabel.setVisible(false);
        // emailIdSeparator.setVisible(false);
        ButtonsignIn.setVisible(true);
        //signInBottomTextBox.setVisible(true);
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        JTextFieldname.setVisible(false);
        //nameSeparator.setVisible(false);
        nameLabel.setVisible(false);
        LabelerrorthrownForEmailId.setVisible(false);
        LabelerrorthrownforerrorPassword.setVisible(false);
        NGOCbx.setVisible(false);
        btnverifyEmail.setVisible(false);
        txtVerifyCode.setVisible(false);
        jButton1.setVisible(false);

    }//GEN-LAST:event_LabeTopsignInMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RadioButtonDonor.setVisible(false);
        RadioButtonreceiver.setVisible(false);
        NGOCbx.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnverifyEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverifyEmailActionPerformed
        // TODO add your handling code here:
       try {
//                logger.log(Level.INFO, "Sending email to new user");
                    JavaMailUtil.sendMail(TextFieldemailId.getText(), JTextFieldname.getText(),verificationCode);
//                      System.out.println()
           JOptionPane.showMessageDialog(this, "Verification Email sent");
                    
                } catch (Exception ex) {
                    
                }
    }//GEN-LAST:event_btnverifyEmailActionPerformed

    private void txtVerifyCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVerifyCodeActionPerformed
        if(verificationCode.equals(txtVerifyCode.getText())){
                       JOptionPane.showMessageDialog(this, " Email verified");
                       check=true;
        }else{
                       JOptionPane.showMessageDialog(this, " please enter correct code");
        }
        txtVerifyCode.setText("");
    }//GEN-LAST:event_txtVerifyCodeActionPerformed
        

public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0, 0, 0));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(171,204,61));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ButtonsignIn;
    private javax.swing.JLabel ButtonsignUp;
    private javax.swing.JPasswordField Fieldpassword;
    private javax.swing.JTextField JTextFieldname;
    private javax.swing.JTextField JTextFielduserName;
    private javax.swing.JLabel LabeTopsignIn;
    private javax.swing.JLabel LabelTopsignUp;
    private javax.swing.JLabel LabelerrorthrownForEmailId;
    private javax.swing.JLabel LabelerrorthrownforerrorPassword;
    private javax.swing.JComboBox<String> NGOCbx;
    private javax.swing.JRadioButton RadioButtonDonor;
    private javax.swing.JRadioButton RadioButtonreceiver;
    private javax.swing.JTextField TextFieldemailId;
    private javax.swing.JLabel Titlelabel;
    private javax.swing.JLabel Usernamelabel;
    private javax.swing.JButton btnverifyEmail;
    private javax.swing.JLabel buttonsexit;
    private javax.swing.JLabel emailIdJlabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBgd;
    private javax.swing.JLabel lblbgd;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordlabel6;
    private javax.swing.JTextField txtVerifyCode;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    

    
}
