/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPages;

//import javafx.scene.paint.Color;
import Backend.DB4OUtil.DB4OUtil;
import Backend.Email;
import Backend.NGO.NGO;
import Backend.SendMessageTwilio;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;

/**
 *
 * @author ms
 */
public class MainHomePage extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    private NGO ngo;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public MainHomePage() {
       
        initComponents();
       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgdImg = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();
        Titlelabel = new javax.swing.JLabel();
        Homelabel = new javax.swing.JLabel();
        Homeimage = new javax.swing.JLabel();
        Adminlabel = new javax.swing.JLabel();
        Adminimage = new javax.swing.JLabel();
        Recieverlabel = new javax.swing.JLabel();
        Receiverimage = new javax.swing.JLabel();
        SysAdminImage = new javax.swing.JLabel();
        SysAdminlabel = new javax.swing.JLabel();
        Donorlabel = new javax.swing.JLabel();
        Donorimage = new javax.swing.JLabel();
        Title1label = new javax.swing.JLabel();
        imgbdg = new javax.swing.JLabel();

        bgdImg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bgdImg.setText("jLabel17");
        bgdImg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bgdImg.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bgdImg.setIconTextGap(2);
        bgdImg.setMaximumSize(new java.awt.Dimension(581, 526));

        setLocationByPlatform(true);
        setUndecorated(true);

        userProcessContainer.setBackground(new java.awt.Color(0, 0, 0));
        userProcessContainer.setMinimumSize(new java.awt.Dimension(974, 682));
        userProcessContainer.setPreferredSize(new java.awt.Dimension(1100, 800));
        userProcessContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titlelabel.setBackground(new java.awt.Color(204, 204, 255));
        Titlelabel.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        Titlelabel.setForeground(new java.awt.Color(255, 255, 255));
        Titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titlelabel.setText("To Someone's Story");
        userProcessContainer.add(Titlelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1099, 70));

        Homelabel.setBackground(new java.awt.Color(255, 255, 255));
        Homelabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Homelabel.setForeground(new java.awt.Color(255, 255, 255));
        Homelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Homelabel.setText("Home");
        userProcessContainer.add(Homelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 140, 50));

        Homeimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Homeimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/homex64asd.png"))); // NOI18N
        Homeimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HomeimageMousePressed(evt);
            }
        });
        userProcessContainer.add(Homeimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 70, 80));

        Adminlabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Adminlabel.setForeground(new java.awt.Color(255, 255, 255));
        Adminlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Adminlabel.setText("Admin");
        userProcessContainer.add(Adminlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 140, 60));

        Adminimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sysadminx64.png"))); // NOI18N
        Adminimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminimageMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AdminimageMousePressed(evt);
            }
        });
        userProcessContainer.add(Adminimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 70, 70));

        Recieverlabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Recieverlabel.setForeground(new java.awt.Color(255, 255, 255));
        Recieverlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Recieverlabel.setText("Receiver");
        userProcessContainer.add(Recieverlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 140, 70));

        Receiverimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/receiverx64.png"))); // NOI18N
        Receiverimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReceiverimageMousePressed(evt);
            }
        });
        userProcessContainer.add(Receiverimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 70, 70));

        SysAdminImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adminx64.png"))); // NOI18N
        SysAdminImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SysAdminImageMousePressed(evt);
            }
        });
        userProcessContainer.add(SysAdminImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 70, -1));

        SysAdminlabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        SysAdminlabel.setForeground(new java.awt.Color(255, 255, 255));
        SysAdminlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SysAdminlabel.setText("Sys Admin");
        userProcessContainer.add(SysAdminlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 140, 60));

        Donorlabel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Donorlabel.setForeground(new java.awt.Color(255, 255, 255));
        Donorlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Donorlabel.setText("Donor");
        userProcessContainer.add(Donorlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 550, 140, 60));

        Donorimage.setBackground(new java.awt.Color(102, 0, 102));
        Donorimage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Donorimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Donorx64.png"))); // NOI18N
        Donorimage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DonorimageMousePressed(evt);
            }
        });
        userProcessContainer.add(Donorimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 544, 70, 70));

        Title1label.setBackground(new java.awt.Color(204, 204, 255));
        Title1label.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        Title1label.setForeground(new java.awt.Color(255, 255, 255));
        Title1label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1label.setText("Change the Ending");
        userProcessContainer.add(Title1label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1099, 70));

        imgbdg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bgd.png"))); // NOI18N
        userProcessContainer.add(imgbdg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProcessContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     
    
    
    
    int xx,xy; private void SysAdminMousePressed(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
     
    } 
    private void AdminimageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminimageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminimageMouseClicked

    private void HomeimageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeimageMousePressed
        // TODO add your handling code here:\
        new InformationPage().show();
    }//GEN-LAST:event_HomeimageMousePressed

    private void SysAdminImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SysAdminImageMousePressed
        // TODO add your handling code here:
        boolean flag = true;
        boolean sysadmin = true;
        new LoginPage(flag,sysadmin).show();
    }//GEN-LAST:event_SysAdminImageMousePressed

    private void AdminimageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminimageMousePressed
        // TODO add your handling code here:
        boolean flag = true;
        boolean admin = true;
        new LoginPage(flag,admin).show();
    }//GEN-LAST:event_AdminimageMousePressed

    private void ReceiverimageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReceiverimageMousePressed
        // TODO add your handling code here:
        new LoginPage().show();
    }//GEN-LAST:event_ReceiverimageMousePressed

    private void DonorimageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DonorimageMousePressed
        // TODO add your handling code here:
        new LoginPage().show();
    }//GEN-LAST:event_DonorimageMousePressed
 
 
    public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(102,102,102));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(102,102,102));
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainHomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adminimage;
    private javax.swing.JLabel Adminlabel;
    private javax.swing.JLabel Donorimage;
    private javax.swing.JLabel Donorlabel;
    private javax.swing.JLabel Homeimage;
    private javax.swing.JLabel Homelabel;
    private javax.swing.JLabel Receiverimage;
    private javax.swing.JLabel Recieverlabel;
    private javax.swing.JLabel SysAdminImage;
    private javax.swing.JLabel SysAdminlabel;
    private javax.swing.JLabel Title1label;
    private javax.swing.JLabel Titlelabel;
    private javax.swing.JLabel bgdImg;
    private javax.swing.JLabel imgbdg;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables

    private void g() {
        JFrame frame = new JFrame("Fireworks");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        frame.setSize(screenSize.width/2, screenSize.height/2);
        frame.setResizable(false);
        frame.setUndecorated(false);
        frame.getRootPane().setWindowDecorationStyle(JRootPane.FRAME);
        frame.setLayout(new BorderLayout());
        JPanel panel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JLabel jLabel = new JLabel("Fireworks By Team: 200 Success");
        jLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
        panel.add(jLabel);
        frame.getContentPane().add(panel, BorderLayout.NORTH);
        //frame.getContentPane().add(new FireworkPanel(), BorderLayout.CENTER);
        frame.setVisible(true);
        Icon imgIcon = new ImageIcon(this.getClass().getResource("/Images/confetti.gif"));
       JLabel label = new JLabel(imgIcon);
      label.setBounds(668, 43, 46, 14); // You can use your own values
        frame.getContentPane().add(label);
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

